#!/bin/bash

echo must be in scratchbox: "sb2 -M /srv/preware/cross-compile/staging/mapping-armv6"

echo List your source files here
SRC=webmyth_service.cpp

echo List the libraries needed
LIBS="-lpdl -lSDL -lpthread"

echo static libs
STATIC_LIBS=libmysqlclient_ARM.a

echo options for PIXI
DEVICEOPTS="-mcpu=arm1136jf-s -mfpu=vfp -mfloat-abi=softfp"

echo itermediate object file
MIDFILE=webmyth_service.o

echo Name your output executable
OUTFILE=webmyth_service_ARM

PALMPDK="/home/wes/Dropbox/development/PalmPDK"

g++ $DEVICEOPTS -o $OUTFILE $SRC $STATIC_LIBS "-I$PALMPDK/include" "-I$PALMPDK/include/SDL" "-L$PALMPDK/device/lib" -Wl,--allow-shlib-undefined $LIBS

echo Then strip the executable with arm-none-linux-gnueabi-bin-strip